### PR TITLE
Fix #108: Fix file ownership on Haiku after rsync

### LINKED ISSUE #108: wrong file permissions on Haiku
Syncing files to the Haiku VM results in them having uid `1001` and gid `118`. Git, however, expects them to have `user:root`, and displays a fatal warning:
```
fatal: detected dubious ownership in repository at '/boot/home/home/runner/work/gha-test/gha-test'
To add an exception for this directory, call:

	git config --global --add safe.directory /boot/home/home/runner/work/gha-test/gha-test
```

Instead of the work-around suggested by git, I think actually using the correct permissions would be a preferable solution. This can be achieved by `chown -R $(id -u):$(id -g) $(pwd)` (because the Haiku user has root powers, as Haiku is a single-user system), or maybe also by tweaking the rsync command line that is used for syncing (I have not looked into this).

See this [config](https://github.com/manxorist/gha-test/blob/03161eaccf0ad0fcfef7189850f5b47ae5d979cb/.github/workflows/Haiku.yml) and [run](https://github.com/manxorist/gha-test/actions/runs/16446458729/job/46479674681) for the error.

*see <https://github.com/cross-platform-actions/action/issues/104#issuecomment-3102886815> for previous discussion*

### PR DESCRIPTION
**Pull request by mr-raj12**
`rsync -auz` preserves numeric UIDs. On the Linux runner files are owned by uid 1001, inside the Haiku VM the user is uid 0.
Git 2.35.2+ won't run in a directory owned by a different user.
The mismatch was always there, just never triggered. `setuptools` 78.1.1 calls `setuptools_scm` earlier in `pip install -e .` than older versions did, so git gets invoked during install and hits the check for the first time.
 
Fix adds a `synchronizePaths` override in the Haiku VM to run `chown` after rsync as same pattern as the existing `setupWorkDirectory` override in the same file, no other OS touched.

Adds a CI job `test-haiku-file-ownership` that boots Haiku and asserts `find . -nouser` returns nothing verifying no files in the work directory are owned by an unresolvable uid after rsync.

  @manxorist identified the issue and proposed the chown approach in #108, this is just the implementation.

  borgbackup/borg#9563 worked around it with
  `git config --global --add safe.directory` on their end, which is how we ran into this.

  Closes #108

### CODE REVIEW

File: src/operating_systems/haiku/qemu_vm.ts [hunk 1]
```diff
@@ -10,6 +10,11 @@ export class Vm extends QemuVm {
     await this.execute(`mkdir -p '${workDirectory}'`)
   }
 
+  override async synchronizePaths(...excludePaths: string[]): Promise<void> {
+    await super.synchronizePaths(...excludePaths)
+    await this.execute(`chown -R $(id -u):$(id -g) '${this.workDirectory}'`)
```
Comment (jacob-carlborg) [inline src/operating_systems/haiku/qemu_vm.ts:15]: Can we run this on all operating systems, even though it won't make any changes other operating systems? I would prefer to keep all operating systems as similar as possible, even though it's unnecessary on other operating systems.

**Comment by jacob-carlborg** [comment]
I would prefer an end-to-end test as well, to make sure it's working properly. A new job in the GitHub action workflow, something like: https://github.com/cross-platform-actions/action/blob/e3d398ccb5a2c7515317e19d84b92baf2ae5ed71/.github/workflows/ci.yml#L306.

File: src/operating_systems/haiku/qemu_vm.ts (hunk 1 above)
Comment (manxorist) [reply src/operating_systems/haiku/qemu_vm.ts:15]: While I agree with the desire to keep operating systems consistent, I think this would be wrong in this particular case.
Haiku is very different in that it is fundamentally a single-user OS. It only "emulates" POSIX owner semantics.
I think keeping this Haiku-only is the better choice.

**Comment by manxorist** [comment]
As mentioned in https://github.com/cross-platform-actions/action/issues/108#issue-3253052742, another option might be to tweak the rsync parameters, but I have not looked at that at all.

File: src/operating_systems/haiku/qemu_vm.ts (hunk 1 above)
Comment (jacob-carlborg) [reply src/operating_systems/haiku/qemu_vm.ts:15]: Fair enough.

**Comment by jacob-carlborg** [comment]
Thanks.
